### ISSUE TITLE
Hey, awesome project, man!😆 I wonder if you will consider some suggestions?

### ISSUE THREAD

**Issue by SeasonLeee** [guojianglin/year-progress-by-native-demo#1]
hey, I tried to play around the UI based on my experience... and here's the result.

![image](https://user-images.githubusercontent.com/13610283/76707353-69870d80-6729-11ea-9d89-025c35a27638.png)

Well, as much as I enjoy the original UI, which is great and creative and you, I think some change couldn't hurt, right?😉

As you can see from the screenshot above, I made several changes, which is,
1. I made the color of title and content text to the same color, which is gray, which is to less contrast than the white in order to adhere to the whole atmosphere the background image try to convey.
2. I increased the font-size of passed number to 80px, which could cause trouble in mobile device but I made it this big just trying to say that, since the key information of this page is to alarm the visitor how many days have passed by, this number should highlighted with different color and different size.
3. I made the percentage to be integer for much more succinct message to whoever reading it.
4. I change the color of the progress bar to adhere to the whole color palette the background image has set.
And the value I used is this:
`linear-gradient(45deg,
#451b24 25%,
#892b32 0,
#892B2F 50%,
#451b24 0,
#451b24 75%,
#892b32 0)`

That's all. Just some minor changes... I hope you like the modification, if you allow, I make a PR for those.😁

**Comment by guojianglin** [comment]
Oh~~~~, so fucking briliant, and it more cool than my design, just pull request, I can't wait to merge it!!!  thank you man!
